/*
 * This code is derived from MyJavaLibrary (http://somelinktomycoollibrary)
 * 
 * If this is an open source Java library, include the proper license and copyright attributions here!
 */


using System.Collections.Generic;

namespace com.discobeard.spriter.dom
{
	/// <summary><p>Java class for SpriterData complex type.</summary>
	/// <remarks>
	/// <p>Java class for SpriterData complex type.
	/// <p>The following schema fragment specifies the expected content contained within this class.
	/// <pre>
	/// &lt;complexType name="SpriterData"&gt;
	/// &lt;complexContent&gt;
	/// &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	/// &lt;sequence&gt;
	/// &lt;element name="folder" type="{}Folder" maxOccurs="unbounded" minOccurs="0"/&gt;
	/// &lt;element name="entity" type="{}Entity" maxOccurs="unbounded" minOccurs="0"/&gt;
	/// &lt;/sequence&gt;
	/// &lt;attribute name="scml_version" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
	/// &lt;attribute name="generator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
	/// &lt;attribute name="generator_version" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
	/// &lt;/restriction&gt;
	/// &lt;/complexContent&gt;
	/// &lt;/complexType&gt;
	/// </pre>
	/// </remarks>
	public class SpriterData
	{
		protected internal IList<Folder> folder;

		protected internal IList<Entity> entity;

		protected internal string scmlVersion;

		protected internal string generator;

		protected internal string generatorVersion;

		//
		// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
		// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
		// Any modifications to this file will be lost upon recompilation of the source schema. 
		// Generated on: 2013.01.18 at 06:33:53 PM MEZ 
		//
		/// <summary>Gets the value of the folder property.</summary>
		/// <remarks>
		/// Gets the value of the folder property.
		/// <p>
		/// This accessor method returns a reference to the live list,
		/// not a snapshot. Therefore any modification you make to the
		/// returned list will be present inside the JAXB object.
		/// This is why there is not a <CODE>set</CODE> method for the folder property.
		/// <p>
		/// For example, to add a new item, do as follows:
		/// <pre>
		/// getFolder().add(newItem);
		/// </pre>
		/// <p>
		/// Objects of the following type(s) are allowed in the list
		/// <see cref="Folder"></see>
		/// </remarks>
		public virtual IList<Folder> getFolder()
		{
			if (folder == null)
			{
				folder = new List<Folder>();
			}
			return this.folder;
		}

		/// <summary>Gets the value of the entity property.</summary>
		/// <remarks>
		/// Gets the value of the entity property.
		/// <p>
		/// This accessor method returns a reference to the live list,
		/// not a snapshot. Therefore any modification you make to the
		/// returned list will be present inside the JAXB object.
		/// This is why there is not a <CODE>set</CODE> method for the entity property.
		/// <p>
		/// For example, to add a new item, do as follows:
		/// <pre>
		/// getEntity().add(newItem);
		/// </pre>
		/// <p>
		/// Objects of the following type(s) are allowed in the list
		/// <see cref="Entity"></see>
		/// </remarks>
		public virtual IList<Entity> getEntity()
		{
			if (entity == null)
			{
				entity = new List<Entity>();
			}
			return this.entity;
		}

		/// <summary>Gets the value of the scmlVersion property.</summary>
		/// <remarks>Gets the value of the scmlVersion property.</remarks>
		/// <returns>
		/// possible object is
		/// <see cref="string"></see>
		/// </returns>
		public virtual string getScmlVersion()
		{
			return scmlVersion;
		}

		/// <summary>Sets the value of the scmlVersion property.</summary>
		/// <remarks>Sets the value of the scmlVersion property.</remarks>
		/// <param name="value">
		/// allowed object is
		/// <see cref="string"></see>
		/// </param>
		public virtual void setScmlVersion(string value)
		{
			this.scmlVersion = value;
		}

		/// <summary>Gets the value of the generator property.</summary>
		/// <remarks>Gets the value of the generator property.</remarks>
		/// <returns>
		/// possible object is
		/// <see cref="string"></see>
		/// </returns>
		public virtual string getGenerator()
		{
			return generator;
		}

		/// <summary>Sets the value of the generator property.</summary>
		/// <remarks>Sets the value of the generator property.</remarks>
		/// <param name="value">
		/// allowed object is
		/// <see cref="string"></see>
		/// </param>
		public virtual void setGenerator(string value)
		{
			this.generator = value;
		}

		/// <summary>Gets the value of the generatorVersion property.</summary>
		/// <remarks>Gets the value of the generatorVersion property.</remarks>
		/// <returns>
		/// possible object is
		/// <see cref="string"></see>
		/// </returns>
		public virtual string getGeneratorVersion()
		{
			return generatorVersion;
		}

		/// <summary>Sets the value of the generatorVersion property.</summary>
		/// <remarks>Sets the value of the generatorVersion property.</remarks>
		/// <param name="value">
		/// allowed object is
		/// <see cref="string"></see>
		/// </param>
		public virtual void setGeneratorVersion(string value)
		{
			this.generatorVersion = value;
		}
	}
}
